# Generated by Django 5.0 on 2023-12-06 17:33

from django.db import migrations

from api.credit import models
from api.user.models import User


def create_default_data(apps, schema_editor):
    apple_manufacturer = models.Manufacturer.objects.get_or_create(
        name="Apple",
    )[0]

    samsung_manufacturer = models.Manufacturer.objects.get_or_create(
        name="Samsung",
    )[0]

    porsche_manufacturer = models.Manufacturer.objects.get_or_create(
        name="Porsche",
    )[0]

    apple_iphone = models.Product.objects.get_or_create(
        name="iPhone 15",
        manufacturer=apple_manufacturer,
    )[0]

    apple_ipad = models.Product.objects.get_or_create(
        name="iPad 10",
        manufacturer=apple_manufacturer,
    )[0]

    apple_air_pods = models.Product.objects.get_or_create(
        name="AirPods 5",
        manufacturer=apple_manufacturer,
    )[0]

    samsung_product = models.Product.objects.get_or_create(
        name="Galaxy S30",
        manufacturer=samsung_manufacturer,
    )[0]

    porsche_product = models.Product.objects.get_or_create(
        name="Taycan",
        manufacturer=porsche_manufacturer,
    )[0]

    contract_1 = models.Contract.objects.get_or_create(
        name="Contract 1",
    )[0]

    contract_2 = models.Contract.objects.get_or_create(
        name="Contract 2",
    )[0]

    contract_3 = models.Contract.objects.get_or_create(
        name="Contract 3",
    )[0]

    admin = User.objects.get(username="admin")

    credit_request_1 = models.CreditRequest.objects.get_or_create(
        name="Credit Request 1",
        contract=contract_1,
        user=admin,
    )[0]

    credit_request_2 = models.CreditRequest.objects.get_or_create(
        name="Credit Request 2",
        contract=contract_2,
        user=admin,
    )[0]

    credit_request_3 = models.CreditRequest.objects.get_or_create(
        name="Credit Request 3",
        contract=contract_3,
        user=admin,
    )[0]

    credit_request_1.products.add(apple_iphone)
    credit_request_1.products.add(apple_ipad)
    credit_request_1.products.add(apple_air_pods)

    credit_request_2.products.add(samsung_product)
    credit_request_2.products.add(apple_air_pods)

    credit_request_3.products.add(porsche_product)
    credit_request_3.products.add(apple_iphone)


class Migration(migrations.Migration):
    dependencies = [("credit", "0001_initial"), ("user", "0002_create_superuser")]

    operations = [
        migrations.RunPython(create_default_data),
    ]
